name: CI

on: [push, pull_request, release]

jobs:
  lint:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint
  build:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo dpkg --add-architecture i386
    - run: wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
    - run: sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport
    - run: sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main"
    - run: sudo apt install --install-recommends winehq-stable
    - run: npm ci
    - run: npm run build
    - uses: actions/upload-artifact@v2
      with:
          name: Installer
          path: out/make/squirrel.windows/x64
